import json, requests, os, time
from datetime import datetime

# Load today's pack generated by Meta AI 6 AM bot
with open('today_posts.json', 'r') as f:
    data = json.load(f)

print(f"Found {len(data.get('celebs', []))} celebs to post")

for celeb in data.get('celebs', []):
    print(f"\nPosting {celeb['name']}...")
    for post in celeb['posts']:
        page_id = os.environ.get(post['page_id_env'])
        token = os.environ.get(post['token_env'])
        
        if not page_id or not token:
            print(f"Skipping {post['page_name']} - no token")
            continue
            
        # Your collage maker will create these images
        # For now bot expects images in /collages folder
        image_path = post.get('image_path', '')
        if not os.path.exists(image_path):
            print(f"Image not found {image_path}, using placeholder")
            continue
        
        url = f"https://graph.facebook.com/v19.0/{page_id}/photos"
        payload = {
            "message": post['caption'],
            "published": False,
            "scheduled_publish_time": post['unix_timestamp'],
            "access_token": token
        }
        
        with open(image_path, 'rb') as img:
            r = requests.post(url, data=payload, files={'source': img})
        
        print(f"{post['page_name']} at {post['scheduled_time']} -> {r.status_code} {r.text}")
        time.sleep(3)  # avoid rate limit

print("Done - all posts scheduled!")
